version: '3.3'

networks:
  backend:
    driver: bridge

volumes:
  mysql: {}

secrets:
  mysql_root_password:
    external: true
  mysql_user:
    external: true
  mysql_password:
    external: true

services:
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: verysecure
      MYSQL_USER: user
      MYSQL_PASSWORD: secure
    ports:
      - 3333:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    networks:
      - backend
  kowl:
    image: quay.io/cloudhut/kowl:master-1d07695
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$KOWL_CONFIG_FILE\" > /tmp/config.yml; /app/kowl"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      KOWL_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:9092"]
    ports:
      - '22222:8080'
    depends_on:
      - kafka
    networks:
      - backend
